name: foodition
description: "HackFest 2024"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.9
  go_router: ^13.0.0
  google_fonts: ^6.1.0
  image_picker: ^1.0.6
  intl: ^0.19.0
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/banner/
    - assets/images/introduction/
    - assets/icons/

flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo-app.png"
